###
### Main Stem Mark-Recapture Calculations 
###

library(car)
library(multcompView)
library(multcomp)
library(ggplot2)
library(lme4)
library(lmerTest)
library(dplyr)
library(emmeans)
library(stringr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(broom)
library(knitr)
library(readxl)
library(writexl)
library(outliers)
library(psych)
library(vtable)
library(lattice)
library(magrittr)
library(mgcv)
library(grid)
library(FSA)

mr_dat = read.csv("Main_Stem_MR_Data.csv")
view(mr_dat)
mr_dat$Reach.Length_mm = as.numeric(mr_dat$Reach.Length_mm)
mr_dat$Length_mm = as.numeric(mr_dat$Length_mm)
mr_dat$Mass_g = as.numeric(mr_dat$Mass_g)
mr_dat$Pass = as.factor(mr_dat$Pass)
